version: '3.0'
services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=agrohack
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"

  agrohack:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=agrohack
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db


