version: '3.0'
services:
  db:
    image: postgres:13-alpine
    environment:
    - POSTGRES_DB=agrohack
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    expose:
      - 5432
